Feature main page
rsredsq/airbnb-demo-frontend pull request #1
Opened 2018-01-05 06:51 UTC by rsredsq

2018-01-05 15:11 UTC, imevro requested changes
неплохо, но структура усложнена на пустом месте

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Footer/Selectors.jsx
> +    <Container>
косяк с неймингом — контейнер относится к сетке, оч неочевидно почему контейнер в колонке лежит

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Footer/index.jsx
> +  <Row>
это чё вообще

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/cards/ExperienceCard.jsx
> +const Price = styled.a`
а почему не вся карточка ссылкой?

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/cards/ExperienceCard.jsx
> +const Rating = styled.label`
почему лейбл? лейбл для форм

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/cards/HomeCard.jsx
> +const RowDescription = styled.div`
а зачем префикс роу, если можно просто дескрипшен?

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/cards/HomeCard.jsx
> +  <Col xs={8} sm={8} md={5} lg={4}>
вынеси за пределы карточки — что будет с компонентом, когда ты эту же карточку захочешь использовать в других колонках?

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/cards/HomeCard.jsx
> +import React from 'react';
зачем карточке лежать в `/cards`, если можно в `Homes/Card.js`?

2018-01-05 15:11 UTC, evgenyrodionov commented on src/Main/index.jsx
> +import ExperiencesSection from './sections/ExperiencesSection';
зачем все эти префиксы и постфиксы секшен секшенс?

2018-01-06 00:01 UTC, rsredsq commented
@evgenyrodionov давай по жесткому плз, я вроде все сделал, и адаптивность тоже

2018-01-06 11:14 UTC, imevro requested changes

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Footer/Selectors.jsx
> +const Dropdown = styled.div`
можно же застилизовать селект через `appearance: none`

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Footer/Socials.jsx
> +const Copyright = () => <p>© Airbnb Inc.</p>;
опусти реакт-компоненты ниже ск, чтобы не смешивалось

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Footer/Socials.jsx
> +  width: 100%;
у дивов по-умолчанию 100%

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Footer/Socials.jsx
> +  min-height: 3.75rem;
зачем?

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Footer/common.jsx
> +import styled from 'styled-components';
common → styled

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Header/index.jsx
> +          <Col xs={2} md={1}>
а зачем тут сетка? плюс очень много вложенности, упрощай

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/Rating.jsx
> +import _ from 'lodash';
импорти только нужную функцию, иначе при билде будет весь лоудеш, а он немало весит

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/Section.jsx
> +      {props.seeAll && (
костыль

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/Section.jsx
> +          See All <img src={arrowRight} alt="See All" width={6} height={10}/>
убери отсюда имейдж, засунь в цсс

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/index.jsx
> +import Explore from './sections/Explore';
убери директорию sections, нахуй она нужна?

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/sections/Experiences/Card.jsx
> +    <div>
параграф

2018-01-06 11:14 UTC, evgenyrodionov commented on src/Main/sections/Experiences/index.jsx
> +const CardColumn = ({ children }) => (
почему не просто column? зачем префикс кард?

2018-01-07 12:53 UTC, imevro approved these changes

2018-01-07 12:53 UTC, merged