Feature homes page
rsredsq/airbnb-demo-frontend pull request #2
Opened 2018-01-10 23:29 UTC by rsredsq

https://airbnb-demo-frontend.now.sh

2018-01-11 14:37 UTC, evgenyrodionov commented
Отступы между текстом в карточках пиздецовые
![image](https://user-images.githubusercontent.com/775692/34830770-f631c49c-f6f5-11e7-91bb-614ba0772f96.png)

---

у хедера странный цвет бордера

---

в футере странные отступы между элементами + внизу все сожралось нахуй

![image](https://user-images.githubusercontent.com/775692/34830790-07bb570a-f6f6-11e7-820a-7b4a5946c781.png)

---

Тут тоже футер неприглядный
![image](https://user-images.githubusercontent.com/775692/34830811-1539c68c-f6f6-11e7-8aba-ca622433a187.png)

2018-01-11 14:37 UTC, evgenyrodionov commented
а, и в хедере тоже между ссылками хуевые расстояния

2018-01-11 14:47 UTC, imevro requested changes

2018-01-11 14:47 UTC, evgenyrodionov commented on package.json
> +    "deploy": "yarn build && now ./build -p && now alias -A ./build/now.json"
now.json можно в корень проекта

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +  renderDatePicker() {
ты объявляешь позже, чем используешь  — не надо так делать

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +const FakeButtons = () => (
поч фейк

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +    console.log(`Dates saved! start date: ${startDate.format()}, end date: ${endDate.format()}`);
ну а почему бы их и не сохранять?

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Homes/Pages.jsx
> +    if (selected) {
главная страница СК https://www.styled-components.com/

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Homes/Pages.jsx
> +  chunk(homes, rowSize).map((row, index) => (
Нахуя??? сеткам плевать сколько внутри элементов, всё встанет нормально

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Homes/Pages.jsx
> +          <Card {...home} />
явное лучше неявного

2018-01-11 14:47 UTC, evgenyrodionov commented on src/Main/Explore/index.jsx
> +      <Card title="Homes" image={bedImage} link="/homes" />
link, а внутри to

2018-01-13 08:54 UTC, rsredsq commented on src/Filters/index.jsx
> +const FakeButtons = () => (
потому что они пока ничего не делают

2018-01-13 08:55 UTC, rsredsq commented on package.json
> +    "deploy": "yarn build && now ./build -p && now alias -A ./build/now.json"
чет не работало, потому что я деплоил из билда, а если в корень кинуть, то будет думать что я и деплоил корень, но еще попорюсь с этим

2018-01-13 09:22 UTC, evgenyrodionov commented on package.json
> +    "deploy": "yarn build && now ./build -p && now alias -A ./build/now.json"
`now build` из директории проекта, потому что

```sh
 ~ $ now --help

  𝚫 now [options] <command | path>

  Commands:

    Cloud

      deploy               [path]      Performs a deployment (default)
      ls | list            [app]       List deployments
      rm | remove          [id]        Remove a deployment
      ln | alias           [id] [url]  Configures aliases for deployments
      domains              [name]      Manages your domain names
      certs                [cmd]       Manages your SSL certificates
      secrets              [name]      Manages your secret environment variables
      dns                  [name]      Manages your DNS records
      logs                 [url]       Displays the logs for a deployment
      scale                [args]      Scales the instance count of a deployment
      help                 [cmd]       Displays complete help for [cmd]

    Administrative

      billing | cc         [cmd]       Manages your credit cards and billing methods
      upgrade | downgrade  [plan]      Upgrades or downgrades your plan
      teams                [team]      Manages your teams
      switch                           Switches between teams and your account
      login                            Login into your account or creates a new one
      logout                           Logout from your account

  Options:

    -h, --help                Output usage information
    -v, --version             Output the version number
    -n, --name                Set the name of the deployment
    -c FILE, --config=FILE    Config file
    -d, --debug               Debug mode [off]
    -f, --force               Force a new deployment even if nothing has changed
    -t TOKEN, --token=TOKEN   Login token
    -L, --login               Configure login
    -l, --links               Copy symlinks without resolving their target
    -p, --public              Deployment is public (`/_src` is exposed) [on for oss, off for premium]
    -e, --env                 Include an env var (e.g.: `-e KEY=value`). Can appear many times.
    -E FILE, --dotenv=FILE    Include env vars from .env file. Defaults to '.env'
    -C, --no-clipboard        Do not attempt to copy URL to clipboard
    -N, --forward-npm         Forward login information to install private npm modules

  Enforcable Types (when both package.json and Dockerfile exist):

    --npm                     Node.js application
    --docker                  Docker container
    --static                  Static file hosting

  Examples:

  – Deploys the current directory

    $ now

  – Deploys a custom path `/usr/src/project`

    $ now /usr/src/project

  – Deploys a GitHub repository

    $ now user/repo#ref

  – Deploys a GitHub, GitLab or Bitbucket repo using its URL

    $ now https://gitlab.com/user/repo

  – Deploys with ENV vars

    $ now -e NODE_ENV=production -e MYSQL_PASSWORD=@mysql-password

  – Displays comprehensive help for the subcommand `list`

    $ now help list
```

2018-01-13 09:23 UTC, evgenyrodionov commented
С этим чё?
https://github.com/rsredsq/airbnb-demo-frontend/pull/2#issuecomment-356952339

С отступами в карточках полнейший кошмар, между кнопками в фильтре три орла пролетят
![image](https://user-images.githubusercontent.com/775692/34904699-868a71c6-f85c-11e7-8e69-0b5d506744a5.png)

Футер ВООБЩЕ не как в макете
![image](https://user-images.githubusercontent.com/775692/34904700-8b9483f0-f85c-11e7-9a71-ec41c4ca4eb6.png)

Календарь не применяет значения

2018-01-13 09:24 UTC, evgenyrodionov commented
Футер все еще хуёвый
![image](https://user-images.githubusercontent.com/775692/34904711-a4f1f792-f85c-11e7-8ed4-0bf02e2dfc8c.png)

2018-01-13 09:24 UTC, evgenyrodionov commented
Тут тоже в карточке проблемы
![image](https://user-images.githubusercontent.com/775692/34904715-aef3e638-f85c-11e7-81a6-473a186dab1f.png)

2018-01-13 09:24 UTC, evgenyrodionov commented
Не могу проверять такую сырую работу

2018-01-13 09:36 UTC, evgenyrodionov commented
Лучше, но футер всё равно не как в макете
![image](https://user-images.githubusercontent.com/775692/34904802-4d7ab5ba-f85e-11e7-87b1-da94ee1d7b5c.png)

Да и тут дырища между кнопками
![image](https://user-images.githubusercontent.com/775692/34904809-587773b8-f85e-11e7-9264-12715bacab4e.png)

Кнопок апплая и кэнсел нету
![image](https://user-images.githubusercontent.com/775692/34904814-658ee810-f85e-11e7-8f78-a0ba6578f711.png)

2018-01-13 09:42 UTC, imevro requested changes

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +const laptopCalendarProps = {
у нас нет терминологии мобайл лаптоп десктоп, только xs/md/lg

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +    this.setState(prevState => ({ open: !prevState.open }));
все булеан идут через `is*`

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +      : laptop ? laptopCalendarProps : desktopCalendarProps;
вложенные тернарники ужасны

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +          <DayPickerRangeController
чё тут за 5 отступа

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +            noBorder
тут просто noBorder

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/DatePicker.jsx
> +            hideKeyboardShortcutsPanel={true}
а тут уже `={true}`

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/helpers.js
> +import isInclusivelyAfterDay from 'react-dates/src/utils/isInclusivelyAfterDay';
НЕЛЬЗЯ ЛЕЗТЬ ВНУТРЬ БИБЛИОТЕКИ

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/helpers.js
> +import isInclusivelyAfterDay from 'react-dates/src/utils/isInclusivelyAfterDay';
иначе можно объебаться как реакт-портал когда-то https://github.com/tajo/react-portal/pull/106

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +  top: 4.9675rem;
красиво)))

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +    if (!startDate || !endDate) return;
нельзя делать нулевые return

2018-01-13 09:42 UTC, evgenyrodionov commented on src/Homes/Pages.jsx
> +    css`
зачем тебе хелпер `css`?

2018-01-13 09:42 UTC, evgenyrodionov commented on src/UI/ModalWindow/index.jsx
> +  flex: 1 0 100%;
распиши, сложно для понимания (

2018-01-13 09:42 UTC, evgenyrodionov commented on src/UI/ModalWindow/index.jsx
> +    const mobile = matchMedia('(max-width: 767px)').matches;
мы не используем max-width

2018-01-13 09:42 UTC, evgenyrodionov commented on src/UI/ModalWindow/index.jsx
> +    if (mobile) return this.renderMobile();
фу так делать — дублирование кода получается

2018-01-13 09:42 UTC, evgenyrodionov commented on src/UI/ModalWindow/index.jsx
> +    if (mobile) return this.renderMobile();
для адаптива есть цсс и медиаквери

2018-01-13 20:53 UTC, rsredsq commented
https://airbnb-demo-frontend-nmtftaburn.now.sh

2018-01-13 22:11 UTC, rsredsq commented
https://airbnb-demo-frontend-gixjbbmsbh.now.sh

2018-01-21 08:21 UTC, imevro requested changes

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/CalendarInfo.jsx
> +  color: ${({ color }) => color};
а зачем ты так делаешь? просто стилизуй кнопку и всё

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/CalendarInfo.jsx
> +const CalendarButton = styled.button`
зачем префикс календарь если ты и так в календаре?

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/helpers.js
> +export function buttonDateFormat(startDate, endDate) {
функции должны быть с действием, с глаголом

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/helpers.js
> +  return `${format(startDate)} – ${format(endDate)}`;
undefined передам, что будет?

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/index.jsx
> +  xsCalendarProps = {
нахуя это в классе хранить?

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/index.jsx
> +    renderCalendarInfo: CalendarInfo(this.cancel, this.saveDates)
нет, откуда тут компонент взялся? Да еще и функцией его вызвал

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/index.jsx
> +    window.removeEventListener('resize', this.close);
wtf

2018-01-21 08:21 UTC, evgenyrodionov commented on src/Filters/DatePicker/index.jsx
> +  buttonTitle() {
опять же, зачем это в классе

2018-01-21 11:32 UTC, rsredsq commented on src/Filters/DatePicker/helpers.js
> +  return `${format(startDate)} – ${format(endDate)}`;
не нужно туда передавать undefined

2018-01-21 12:37 UTC, rsredsq commented on src/Filters/DatePicker/index.jsx
> +    renderCalendarInfo: CalendarInfo(this.cancel, this.saveDates)
ну мне нужно пропс закинуть в дейт пикер, функцию, которая будет рисовать эту панель внизу. CalendarInfo создает такой компонент, поэтому я её и вызываю. А насчет зачем хранить это в классе, потому что мне нужно передать туда функции cancel и saveDates.

2018-01-21 12:39 UTC, rsredsq commented on src/Filters/DatePicker/index.jsx
> +  xsCalendarProps = {
отому что мне нужно передать функции cancel и saveDates в renderCalendarInfo

2018-01-22 14:35 UTC, imevro requested changes

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Filters/DatePicker/CalendarInfo.jsx
> +export const createCalendarInfo = (onClose, onApply) => {
это же компонент, почему глаголом?

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Filters/DatePicker/CalendarInfo.jsx
>    return () => (
зачем тут функция возвращается?

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Filters/DatePicker/helpers.js
> +  return `${format(startDate)} – ${format(endDate)}`;
так если выбрано только одно, то второе будет андефайнед лол

2018-01-22 17:03 UTC, zhelezkov commented on src/Filters/DatePicker/helpers.js
> +  return `${format(startDate)} – ${format(endDate)}`;
[вот здесь есть проверка, что не нулл](https://github.com/rsredsq/airbnb-demo-frontend/pull/2/commits/d39b75e2681c6d9f13aad9076b717b1b88bfe31f#diff-fe9163e7b423fffca255c2ec92bff8e5R4). ну туда не может андефайнед прососаться никак, и не нужно туда такое просасывать. я правда не вижу смысла ставить там ифчик на даты, это функция утилита прост, иначе с таким же успехом можно на все функции понаписать ассерты.

2018-01-22 19:01 UTC, imevro approved these changes

2018-01-22 19:01 UTC, merged