Feature all filters
rsredsq/airbnb-demo-frontend pull request #3
Opened 2018-01-23 23:20 UTC by rsredsq

начал делать фильтры, также впилил еслинт с конфигами
https://airbnb-demo-frontend-xpcltcbxol.now.sh

2018-01-24 10:03 UTC, evgenyrodionov commented
А чё за дыра такая? 
![image](https://user-images.githubusercontent.com/775692/35326203-fecb2466-0106-11e8-84c6-440e3ee4b53f.png)

2018-01-24 10:04 UTC, evgenyrodionov commented
Если я сейчас попробую нажать на Guests, то фильтр просто закроется, а Guests не откроется
![image](https://user-images.githubusercontent.com/775692/35326229-0cc43378-0107-11e8-85ac-0c21eae46743.png)

2018-01-24 10:04 UTC, evgenyrodionov commented
Некрасиво оч смотрится, перепроверь по макету и кнопка минуса почему-то не выключена, я могу взять с собой -9 детей
![image](https://user-images.githubusercontent.com/775692/35326250-1e1e0a2c-0107-11e8-89a3-4b6dd067f0d4.png)

2018-01-24 10:05 UTC, evgenyrodionov commented
Тут ваще пизда
![image](https://user-images.githubusercontent.com/775692/35326262-2f63268c-0107-11e8-89be-bff0eaa90753.png)

????
![image](https://user-images.githubusercontent.com/775692/35326272-355d33c0-0107-11e8-97c6-f668a3c2ecbf.png)

2018-01-24 10:06 UTC, evgenyrodionov commented
Слегка не понял что мне проверять в итоге, если ничего нет

2018-01-26 00:11 UTC, rsredsq commented
Сейчас полностью работают 4 фильтра
Остальные скрыл, как ты и говорил
Долго поролся как фильтры удобней организовать, пришел сейчас к такому виду, вроде бы все супер удобно получается. Надеюсь дальше дело пойдет быстрее

https://airbnb-demo-frontend-jwpwkrcjaw.now.sh

2018-01-26 15:57 UTC, evgenyrodionov commented
Сделай лейблом
![image](https://user-images.githubusercontent.com/775692/35448146-96743144-02ca-11e8-8084-0ae502b8f9ac.png)

Значения не обновляются
![image](https://user-images.githubusercontent.com/775692/35448156-a1bd10fc-02ca-11e8-8d26-aa011971b44f.png)

2018-01-26 15:57 UTC, evgenyrodionov commented
Чё со стилями карточек?
![image](https://user-images.githubusercontent.com/775692/35448216-c58af92c-02ca-11e8-9f33-2163bf445f83.png)

2018-01-26 16:07 UTC, imevro requested changes
чё-т ты наусложнял

2018-01-26 16:07 UTC, imevro commented on src/Filters/Container.jsx
> +export default class FilterContainer extends React.Component {
чё за контейнеры?

2018-01-26 16:07 UTC, imevro commented on src/Filters/Container.jsx
> +        {React.Children.map(this.props.children, (child) => {
лол втф? зачем?

2018-01-26 16:07 UTC, imevro commented on src/Filters/Container.jsx
> +          innerRef={(toggleButton) => {
зачем? рефы это зло

2018-01-26 16:07 UTC, evgenyrodionov commented on src/Filters/InstantBook/Controller.jsx
> +import InstantBook from './index';
а почему из индекса? не круто ваще

2018-01-26 16:07 UTC, evgenyrodionov commented on src/Filters/Price/index.jsx
> +injectGlobal`
выглядит как костыль, засунь просто в .css файл

2018-01-26 16:07 UTC, evgenyrodionov commented on src/Filters/Price/index.jsx
> +const Handle = styled.div`
почему не кнопка?

2018-01-26 16:07 UTC, evgenyrodionov commented on src/Filters/Rooms/Controller.jsx
> +import Rooms from './index';
это вообще говно какое-то если надо из индекса импортить

2018-01-26 16:07 UTC, evgenyrodionov commented on src/Filters/index.jsx
> +const WrapperIngestor = ({
што здесь происходит

2018-01-26 19:28 UTC, rsredsq commented on src/Filters/Price/index.jsx
> +const Handle = styled.div`
это же не кнопка, а тип ручка

2018-01-26 19:38 UTC, rsredsq commented on src/Filters/Container.jsx
> +        {React.Children.map(this.props.children, (child) => {
чтобы пропсы заинжектить в чилдренов

2018-01-26 19:41 UTC, rsredsq commented on src/Filters/index.jsx
> +const WrapperIngestor = ({
Тут на самом деле все очень просто, оно просто пихает в фильтры пропсы, сгенеренные по их имени. За счет этого у меня будет всегда имя компонента, которое отправило действие наверх, и это удобно разруливать, например можно легко в правильный стейт ставиться. Без этого в фильтре бы пришлось имя например постоянно передавать, а так все само подсасывается

2018-01-27 08:49 UTC, rsredsq commented
https://airbnb-demo-frontend-xwntdmoooy.now.sh/

more filters в процессе..

2018-01-27 13:12 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35472254-cabdf9b4-037c-11e8-96f3-b1c88cd03ece.png)

Все еще не так как нужно
![image](https://user-images.githubusercontent.com/775692/35472258-d280c5f0-037c-11e8-8c8e-e1167d2c9fc6.png)

Фром 542 ту 1000 кого? Африканских денег? + используй react-intl
![image](https://user-images.githubusercontent.com/775692/35472260-e320a574-037c-11e8-90ef-356d5c435b11.png)

2018-01-27 13:17 UTC, imevro requested changes
в целом пиздато

2018-01-27 13:17 UTC, evgenyrodionov commented on src/Filters/Guests/Picker.jsx
> +import ValueChanger from '../../UI/ValueChanger';
так-то любой элемент формы это вэлью ченджер)

2018-01-27 13:17 UTC, evgenyrodionov commented on src/Filters/Guests/index.jsx
> +    ...initialState,
лол, поч не state = initialState?

2018-01-27 20:09 UTC, rsredsq commented
https://airbnb-demo-frontend-tbvkgdohlz.now.sh

2018-01-27 20:16 UTC, rsredsq commented
https://airbnb-demo-frontend-vgcwrazvti.now.sh

2018-01-28 18:40 UTC, imevro approved these changes

2018-01-28 18:40 UTC, merged