Feature api
rsredsq/airbnb-demo-frontend pull request #4
Opened 2018-01-31 20:22 UTC by rsredsq

https://airbnb-demo-frontend-wyrgospzwv.now.sh

2018-02-01 16:50 UTC, imevro requested changes

2018-02-01 16:50 UTC, evgenyrodionov commented on src/Homes/api.js
> +      return 'Entire house';
а объектом?

2018-02-01 16:50 UTC, evgenyrodionov commented on src/Homes/api.js
> +        id: home.id,
вынеси в функцию тоже)

2018-02-01 16:50 UTC, evgenyrodionov commented on src/Homes/api.js
> +    .then(res => res.items)
лол, а зачем?

2018-02-01 19:46 UTC, rsredsq commented
деплой не прикладываю, тк ничего визуально не изменилось

2018-02-03 10:22 UTC, imevro approved these changes

2018-02-03 10:22 UTC, merged